remote_theme: pages-themes/leap-day@v0.2.0
leap-day:
  skin: dark
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
markdown: GFM
avatar: "./assets/logo.jpg"
round-avatar: true
title-on-all-pages: false
page-col: "#000000"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"
